### ISSUE TITLE
Initial chain implementation

### ISSUE THREAD

**Issue by hexfusion** [ava-labs/spacesvm-rs#32]
This issue covers tracking all the logic required for the VM to properly create and manage a blockchain in parity with more modern custom projects such as blob and spaces vm. The intial chain impl does not cover a full mempool implementation or tx signatures or a full genesis.

chain/
- [x] activity @hexfusion #49
- [x] base_tx @hexfusion #49
- [x] block @hexfusion #49 
- [x] builder
~~- [ ] codec~~
~~- [ ] common_tx~~
- [x] crypto @hexfusion #49 
- [x] decoder
~~- [ ] genesis~~
~~- [ ] mempool~~
- [x] set_tx @hexfusion #49 
- [x] storage @hexfusion #49 
~~- [x] transfer_tx~~
- [x] txn @hexfusion #49 
- [x] unsigned_tx @hexfusion #49 
- [x] vm @hexfusion #49
